name: SheepRL CPU tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

defaults:
  run:
    shell: bash

jobs:
  cpu-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            setup.py

      - name: Create venv
        run: |
          python -m venv env

      - name: Install packages Windows
        if: runner.os == 'Windows'
        run: |
          env\\Scripts\\activate
          echo ${{env.VIRTUAL_ENV}}
          echo ${{env.virtual_env}}
          echo $VIRTUAL_ENV
          echo %VIRTUAL_ENV%
          pip install swig
          pip install -e .[atari,box2d,test,dev]

      - name: Install packages Linux
        if: runner.os != 'Windows'
        run: |
          source env/bin/activate
          pip install swig
          pip install -e .[atari,box2d,test,dev]

      - name: Run tests Windows
        if: runner.os == 'Windows'
        run: |
          env\\Scripts\\activate
          python tests/run_tests.py

      - name: Run tests Linux
        if: runner.os != 'Windows'
        run: |
          source env/bin/activate
          python tests/run_tests.py
